[package]
name = "flutterbug"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
memchr = "2.3.3"
parking_lot = { version = "0.11.0", optional = true }
tokio = { version = "0.2.22", features = ["dns", "io-util", "tcp"], optional = true }

[features]
default = []
async = ["tokio"]
pl = ["parking_lot", "tokio/pl"]
