[package]
name = "breadx"
version = "0.1.6"
authors = ["John 'not_a_seagull' Nunley <jtnunley01@gmail.com>"]
edition = "2018"
description = "Implementation of the X Window System Protocol"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/not-a-seagull/breadx#readme"
repository = "https://github.com/not-a-seagull/breadx"

[dependencies]
async-io = { version = "1.1.0", optional = true }
async-net = { version = "1.5.0", optional = true }
blocking = { version = "1.0.2", optional = true }
bytemuck = "1.4.1"
cfg-if = "0.1.10"
const_fn = "0.4.3"
cty = "0.2.1"
futures-io = { version = "0.3.6", optional = true }
futures-lite = { version = "1.11.2", optional = true }
hashbrown = "0.9.1"
image = { version = "0.23.12", default-features = false, optional = true }
log = "0.4"
memchr = { version = "2.3.3", default-features = false }
ref_slice = "1.2.0"
tinyvec = { version = "1.1.0-alpha", features = ["alloc"] }

[target.'cfg(unix)'.dependencies]
nix = "0.19.0"

[dev-dependencies]
env_logger = "0.8.1"
image = { version = "0.23.12", default-features = false, features = ["jpeg"] }

[features]
# Optimizations and features
default = ["std"]
async = ["std", "async-io", "async-net", "blocking", "futures-io", "futures-lite"]
image-support = ["image", "std"]
std = ["memchr/std"]

# Extensions
bigreq = []
damage = ["fixes"]
dpms = []
dri2 = []
dri3 = []
fixes = ["render", "shape"]
ge = []
glx = []
present = ["randr", "fixes", "sync"]
print = []
randr = ["render"]
record = []
render = []
res = []
screensaver = []
selinux = []
shape = []
shm = []
sync = []
xevie = []
xf86dri = []
xf86vidmode = []
xinerama = []
#xkb = []
xtest = []
xvmc = ["xv"]
xv = ["shm"]
all-extensions = ["bigreq", "damage", "dpms", "dri2", "dri3", "fixes", "ge", "glx", "present", "print", "randr", "record", "render", "res", "screensaver", "selinux", "shape", "shm", "sync", "xevie", "xf86dri", "xf86vidmode", "xinerama", "xtest", "xvmc", "xv"]

[package.metadata.docs.rs]
features = ["async", "all-extensions"]
rustdoc-args = ["-Z", "unstable-options", "--extend-css", "tutorials/style.css"]
