[package]
name = "flutterbug"
version = "0.3.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.5", optional = true }
async-trait = { version = "0.1.41", optional = true }
bytemuck = "1.4.1"
cfg-if = "0.1.10"
cstr_core = { version = "0.2.2", features = ["alloc"] }
cty = "0.2.1"
hashbrown = "0.9.1"
log = "0.4"
memchr = "2.3.3"
scopeguard = "1.1.0"
tinyvec = { version = "1.1.0-alpha", features = ["alloc"] }

[dev-dependencies]
env_logger = "0.8.1"

[features]
default = ["std"]
async = ["std", "async-std", "async-trait"]
std = []
