[package]
name = "flutterbug"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.4.1"
memchr = "2.3.3"
log = "0.4"
parking_lot = { version = "0.11.0", optional = true }
smallvec = "1.4.0"
tokio = { version = "0.2.22", features = ["dns", "io-util", "tcp"], optional = true }

[features]
default = []
async = ["tokio"]
pl = ["parking_lot", "tokio/parking_lot"]
