[package]
name = "breadx"
version = "0.0.3"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"
description = "Implementation of the X Window System Protocol"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/not-a-seagull/breadx"
repository = "https://github.com/not-a-seagull/breadx#readme"

[dependencies]
async-io = { version = "1.1.0", optional = true }
async-net = { version = "1.5.0", optional = true }
async-trait = { version = "0.1.41", optional = true }
bytemuck = "1.4.1"
cfg-if = "0.1.10"
const_fn = "0.4.3"
cty = "0.2.1"
futures-io = { version = "0.3.6", optional = true }
futures-lite = { version = "1.11.2", optional = true }
hashbrown = "0.9.1"
image = { version = "0.23.12", default-features = false, optional = true }
log = "0.4"
memchr = "2.3.3"
rayon = { version = "1.5.0", optional = true }
tinyvec = { version = "1.1.0-alpha", features = ["alloc"] }

[dev-dependencies]
env_logger = "0.8.1"

[features]
default = ["std"]
async = ["std", "async-io", "async-net", "async-trait", "futures-io", "futures-lite"]
image-support = ["image"]
parallel = ["rayon", "std"]
std = []
