[package]
name = "flutterbug"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.5", optional = true }
async-trait = { version = "0.1.41", optional = true }
bytemuck = "1.4.1"
cfg-if = "0.1.10"
memchr = "2.3.3"
log = "0.4"
tinyvec = { version = "1.1.0-alpha", features = ["alloc"] }

[features]
default = ["std"]
async = ["std", "async-std", "async-trait"]
std = []
